### ISSUE TITLE
Problems with locale gl

### ISSUE THREAD

**Issue by javierojealimia** [javagalician/javagalician-java6#1]
I install the library JavaGalician in my Java_Home/jre/lib/ext and I have this test

final String myDateStr = DateFormat.getDateInstance(DateFormat.FULL, glLocale).format(new Date());
System.out.println(myDateStr);

and the result is correct (luns 13 de abril de 2015). However, I have this other code for obtain all the months and not working

final Locale glLocale = new Locale("gl","ES");
String[] months = new DateFormatSymbols(glLocale).getMonths();
for (int i = 0; i < months.length; i++) {
    String month = months[i];
    System.out.println("month = " + month);
    monthsList .add(months[i]);
}

and the result is in English:

month = January
month = February
month = March
month = April
month = May
month = June
month = July
month = August
month = September
month = October
month = November
month = December

**Comment by danielfernandez** [comment]
Calling the `new DateFormatSymbols(...)` constructor is not the recommended way to obtain an instance of this class, as explained at the JavaDoc API for the class. By doing so, only those locales provided by the JVM itself are covered, and not those implemented by means of external _providers_ (as is the case).

If you want to obtain a Galician-enabled instance, you should do:

``` java
DateFormatSymbols dfs = DateFormatSymbols.getInstance(glLocale);
String[] months = dfs.getMonths();
```

**Comment by javierojealimia** [comment]
It works 
Thanks
